ALTER TABLE "platform_settings" ADD COLUMN "autoPricingEnabled" BOOLEAN NOT NULL DEFAULT false,
 ADD COLUMN "baseDeliveryFee" DECIMAL(10,2) NOT NULL DEFAULT 0,
 ADD COLUMN "perKmFee" DECIMAL(10,2) NOT NULL DEFAULT 0,
 ADD COLUMN "captainSharePercentage" DECIMAL(10,2) NOT NULL DEFAULT 100;
ALTER TABLE "orders" ADD COLUMN "autoPriced" BOOLEAN NOT NULL DEFAULT false,
 ADD COLUMN "captainSharePercentage" DECIMAL(10,2) NOT NULL DEFAULT 100;
