import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { cancelCustomRequest, createCustomRequest, listMyCustomRequests, respondToCustomRequest, useMutation, useResource, useStores, useToast } from '@/hooks/useApi';
import { CustomRequestStatus, type CreateCustomRequestInput } from '@samou-go/shared-types';
import { ScreenShell } from '@/components/ScreenShell';

export function CustomRequestsScreen() {
  const toast = useToast(); const navigate = useNavigate(); const stores = useStores({ pageSize: 100 });
  const requests = useResource('my-custom-requests', signal => listMyCustomRequests({}, signal), { pollMs: 15_000 });
  const create = useMutation<CreateCustomRequestInput, Awaited<ReturnType<typeof createCustomRequest>>>((input, signal) => createCustomRequest(input, signal));
  const [storeId, setStoreId] = useState(''); const [description, setDescription] = useState('');
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!storeId || !description.trim()) return; const result = await create.run({ storeId, description: description.trim() }); if (result) { setDescription(''); requests.reload(); toast.success('تم إرسال الطلب', 'Request sent'); } else toast.error('تعذّر إرسال الطلب', create.error?.localizedMessage ?? 'Try again'); };
  const respond = async (id: string, action: 'ACCEPT' | 'REJECT') => { try { await respondToCustomRequest(id, { action }); requests.reload(); toast.success('تم تحديث الطلب', 'Request updated'); } catch (error) { toast.error('تعذّر تحديث الطلب', error instanceof Error ? error.message : 'Try again'); } };
  const cancel = async (id: string) => { try { await cancelCustomRequest(id); requests.reload(); } catch (error) { toast.error('تعذّر الإلغاء', error instanceof Error ? error.message : 'Try again'); } };
  return <ScreenShell title="طلبات مخصصة" subtitle="Custom requests"><div className="space-y-4 px-4 pb-8"><button type="button" onClick={() => navigate(-1)} className="text-xs font-bold text-brand">← رجوع</button><form onSubmit={event => void submit(event)} className="rounded-2xl border border-line bg-surface p-4 shadow-card"><h2 className="text-sm font-extrabold">اطلب شيئاً غير موجود في القائمة</h2><select value={storeId} onChange={event => setStoreId(event.target.value)} className="input-field mt-3" required><option value="">اختر المتجر</option>{stores.data?.items.map(store => <option key={store.id} value={store.id}>{store.nameAr}</option>)}</select><textarea value={description} onChange={event => setDescription(event.target.value)} className="input-field mt-2 min-h-24" placeholder="اكتب طلبك بالتفصيل" required /><button disabled={create.pending} className="mt-3 rounded-xl bg-brand px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50">إرسال الطلب</button></form><section className="space-y-3">{requests.data?.items.map(request => <article key={request.id} className="rounded-2xl border border-line bg-surface p-4 shadow-card"><div className="flex justify-between gap-3"><b>{request.store.nameAr}</b><span className="text-xs text-ink-muted">{request.status}</span></div><p className="mt-2 text-sm">{request.description}</p>{request.offeredPrice !== null && <p dir="ltr" className="mt-2 font-extrabold">₪{request.offeredPrice.toFixed(2)} {request.offerNote}</p>}{request.status === CustomRequestStatus.PRICE_OFFERED && <div className="mt-3 flex gap-2"><button onClick={() => void respond(request.id, 'ACCEPT')} className="rounded-lg bg-brand px-3 py-2 text-xs font-bold text-white">قبول</button><button onClick={() => void respond(request.id, 'REJECT')} className="rounded-lg border border-line px-3 py-2 text-xs font-bold">رفض</button></div>}{request.status === CustomRequestStatus.PENDING && <button onClick={() => void cancel(request.id)} className="mt-3 text-xs font-bold text-danger">إلغاء الطلب</button>}</article>)}{!requests.loading && !requests.data?.items.length && <p className="py-8 text-center text-sm text-ink-muted">لا توجد طلبات مخصصة بعد</p>}</section></div></ScreenShell>;
}
